builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE
      - config.toml

dockers:
  - goos: linux
    goarch: amd64
    ids:
    - cic-custodial
    image_templates:
    - "ghcr.io/grassrootseconomics/cic-custodial/cic-custodial:latest"
    - "ghcr.io/grassrootseconomics/cic-custodial/cic-custodial:{{ .Tag }}"
    dockerfile: Dockerfile
    extra_files:
    - config.toml
  