builds:
  - id: linux-amd64
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd
    ldflags:
      - -s -w
    binary: cic-custodial

archives:
  - format: tar.gz
    files:
      - LICENSE
      - config.toml
