[service]
address = ":5000"
# Exposes Go process Prometheus metrics
# /metrics endpoint
metrics = true
docs    = false

[chain]
rpc_endpoint     = ""
testnet          = true
registry_address = ""

[system]
private_key = ""
public_key  = ""

[postgres]
dsn = ""

[redis]
# Used for locks and the Noncestore
# Ideally use DB 1
dsn           = ""
min_idle_conn = 5

[asynq]
# Exclusively used by the asynq tasker
# Ideally use DB 0
dsn                = ""
task_retention_hrs = 24
worker_count       = 15

[jetstream]
endpoint = ""