[service]
address = ":5005"
# Exposes Prometheus metrics
# /metrics endpoint
metrics = true

[chain]
rpc_endpoint = "https://rpc.alfajores.celo.grassecon.net"
testnet = true

# System default values
# Valus are in wei unless otherwise stated
[system]
# The giftable token is a training voucher
# Every new user is given 5 DGFT
gas_faucet = "0xf2a1fc19Ad275A0EAe3445798761FeD1Eea725d5"
giftable_token_address = "0xB92463E2262E700e29c16416270c9Fdfa17934D7"
giftable_token_value = 5000000
gas_refill_threshold = 20000000000000000
gas_refill_value = 10000000000000000
# Every custodial account is given 2 KES worth of CELO
giftable_gas_value = 10000000000000000
# System private key
# Should always be toped up
private_key = "95f04bc8321cbf693db9cc2bc063411bbd8bee0e4a03dea096c755d8bcca42c6"
lock_prefix = "lock:"
public_key = "0x0577AE5A3547AC753aC499E282557CE0275a4942"
token_decimals = 6
token_transfer_gas_limit = 200000
account_index = "0x1e041282695C66944BfC53cabce947cf35CEaf87"

[postgres]
debug = false
dsn = "postgres://postgres:postgres@localhost:5432/cic_custodial"

[redis]
debug = false
dsn = "redis://localhost:6379/1"
min_idle_conn = 5

[asynq]
worker_count = 15
debug = false
dsn = "redis://localhost:6379/0"
task_retention_hrs = 24

# https://docs.nats.io/
[jetstream]
endpoint               = "nats://localhost:4222"
# Duration JetStream should keep the message before remocing it from the persistent store
persist_duration_hours = 48
# Duration to ignore duplicate transactions (e.g. due to restart)
dedup_duration_hours   = 6