[service]
debug = true
address = ":5000"

[chain]
endpoint = "https://rpc.sarafu.network"

[admin]
public = "0x80097c773B3E83472FC7952c5206a7DB35d42bEF"
key = "a6af6c597c614e3c8ee4b7638ab7c3f737aece3773a5413ca8caf4338e6b06d1"

[redis]
dsn = "127.0.0.1:6379"

[keystore]
provider = "postgres"
dsn = "postgres://postgres:postgres@localhost:5432/cic_custodial"

[noncestore]
provider = "redis"
