[service]
address = ":5005"
# Exposes Go process Prometheus metrics
# /metrics endpoint
metrics = true

[chain]
rpc_endpoint = ""
testnet = true
devnet = false

[system]
# System default values

# Gas values are in wei with 18 d.p. precision unless otherwise stated
# Token values are in wei with 6 d.p. precision unless otherwise stated

# All addresses MUST be checksumed
account_index_address = ""
gas_faucet_address = ""
gas_refill_threshold = 2500000000000000
gas_refill_value = 10000000000000000
giftable_gas_value = 10000000000000000
giftable_token_address = ""
giftable_token_value = 5000000
# System private key
# Should always be toped up
private_key = ""
public_key = ""
token_decimals = 6
token_transfer_gas_limit = 200000

[postgres]
dsn = ""

[redis]
# Used for locks and the Noncestore
# Ideally use DB 1
dsn = ""
min_idle_conn = 5

[asynq]
# Exclusively used by the asynq tasker
# Ideally use DB 0
dsn = ""
task_retention_hrs = 24
worker_count = 15

[jetstream]
endpoint               = ""
persist_duration_hrs = 48
dedup_duration_hrs   = 6