version: '3.9'
services:
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cic-custodial-redis:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5      
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cic_custodial
    volumes:
      - cic-custodial-pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  asynqmon:
    image: hibiken/asynqmon
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      redis: 
        condition: service_healthy      
  cic-custodial:
    image: ghcr.io/grassrootseconomics/cic-custodial/cic-custodial:latest
    restart: unless-stopped
    depends_on:
      postgres: 
        condition: service_healthy
      redis: 
        condition: service_healthy        
    env_file:
      - .env
    ports:
      - '5000:5000'
volumes:
  cic-custodial-pg:
    driver: local
  cic-custodial-redis:
    driver: local