name: binary_release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Workaround Git Security Warning
        run: |
          # Workaround a bug in github actions:
          # https://github.com/actions/runner-images/issues/6775.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"          

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
